# Generated by Django 5.1.7 on 2025-05-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('has_dimmer', models.BooleanField(default=False, verbose_name='Поддержка диммера')),
                ('power_watts', models.PositiveIntegerField(verbose_name='Мощность (Вт)')),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота (см)')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('lamp_type', models.CharField(choices=[('table', 'Настольная'), ('floor', 'Напольная'), ('wall', 'Настенная'), ('ceiling', 'Потолочная'), ('other', 'Другая')], max_length=20, verbose_name='Тип лампы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Лампа',
                'verbose_name_plural': 'Лампы',
                'ordering': ['-created_at'],
            },
        ),
    ]
