version: '3.9'

services:
  web:
    build: .
    command: gunicorn lamp_catalog.wsgi:application --bind 0.0.0.0:9000
    volumes:
      - .:/app
      - sqlite_data:/app/db  # Volume для базы
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - web

volumes:
  sqlite_data:
